spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db_changelog/changelog.yaml

server:
  port: 8080

schedulers:
  cronExpression: 0 0 0 * * ?

limit: 10000